// 도시별 시간대 및 시간 기준 데이터
export interface CityTimezoneData {
  id: string
  city: string
  country: string
  timezone: string
  utcOffset: number
  timeStandard: "동경135도" | "동경127.5도" | "서머타임"
  useDST?: boolean // 서머타임 사용 여부
}

// 주요 도시 데이터 - 시간대별로 정렬하고 각 시간대마다 최소 하나의 나라 포함
export const CITY_TIMEZONE_DATA: CityTimezoneData[] = [
  // UTC-12
  {
    id: "baker_island",
    city: "베이커 섬",
    country: "미국령",
    timezone: "Etc/GMT+12",
    utcOffset: -12,
    timeStandard: "서머타임",
  },

  // UTC-11
  {
    id: "pago_pago",
    city: "파고파고",
    country: "미국령 사모아",
    timezone: "Pacific/Pago_Pago",
    utcOffset: -11,
    timeStandard: "서머타임",
  },
  {
    id: "niue",
    city: "니우에",
    country: "니우에",
    timezone: "Pacific/Niue",
    utcOffset: -11,
    timeStandard: "서머타임",
  },

  // UTC-10
  {
    id: "honolulu",
    city: "호놀룰루",
    country: "미국 하와이",
    timezone: "Pacific/Honolulu",
    utcOffset: -10,
    timeStandard: "서머타임",
  },
  {
    id: "tahiti",
    city: "타히티",
    country: "프랑스령 폴리네시아",
    timezone: "Pacific/Tahiti",
    utcOffset: -10,
    timeStandard: "서머타임",
  },

  // UTC-9
  {
    id: "anchorage",
    city: "앵커리지",
    country: "미국 알래스카",
    timezone: "America/Anchorage",
    utcOffset: -9,
    timeStandard: "서머타임",
    useDST: true,
  },
  {
    id: "gambier",
    city: "감비에 제도",
    country: "프랑스령 폴리네시아",
    timezone: "Pacific/Gambier",
    utcOffset: -9,
    timeStandard: "서머타임",
  },

  // UTC-8
  {
    id: "los_angeles",
    city: "로스앤젤레스",
    country: "미국",
    timezone: "America/Los_Angeles",
    utcOffset: -8,
    timeStandard: "서머타임",
    useDST: true,
  },
  {
    id: "vancouver",
    city: "밴쿠버",
    country: "캐나다",
    timezone: "America/Vancouver",
    utcOffset: -8,
    timeStandard: "서머타임",
    useDST: true,
  },
  {
    id: "tijuana",
    city: "티후아나",
    country: "멕시코",
    timezone: "America/Tijuana",
    utcOffset: -8,
    timeStandard: "서머타임",
    useDST: true,
  },

  // UTC-7
  {
    id: "denver",
    city: "덴버",
    country: "미국",
    timezone: "America/Denver",
    utcOffset: -7,
    timeStandard: "서머타임",
    useDST: true,
  },
  {
    id: "phoenix",
    city: "피닉스",
    country: "미국 애리조나",
    timezone: "America/Phoenix",
    utcOffset: -7,
    timeStandard: "서머타임",
  },
  {
    id: "edmonton",
    city: "에드먼턴",
    country: "캐나다",
    timezone: "America/Edmonton",
    utcOffset: -7,
    timeStandard: "서머타임",
    useDST: true,
  },
  {
    id: "hermosillo",
    city: "에르모시요",
    country: "멕시코",
    timezone: "America/Hermosillo",
    utcOffset: -7,
    timeStandard: "서머타임",
  },

  // UTC-6
  {
    id: "chicago",
    city: "시카고",
    country: "미국",
    timezone: "America/Chicago",
    utcOffset: -6,
    timeStandard: "서머타임",
    useDST: true,
  },
  {
    id: "mexico_city",
    city: "멕시코시티",
    country: "멕시코",
    timezone: "America/Mexico_City",
    utcOffset: -6,
    timeStandard: "서머타임",
    useDST: true,
  },
  {
    id: "winnipeg",
    city: "위니펙",
    country: "캐나다",
    timezone: "America/Winnipeg",
    utcOffset: -6,
    timeStandard: "서머타임",
    useDST: true,
  },
  {
    id: "san_salvador",
    city: "산살바도르",
    country: "엘살바도르",
    timezone: "America/El_Salvador",
    utcOffset: -6,
    timeStandard: "서머타임",
  },
  {
    id: "guatemala",
    city: "과테말라시티",
    country: "과테말라",
    timezone: "America/Guatemala",
    utcOffset: -6,
    timeStandard: "서머타임",
  },
  {
    id: "managua",
    city: "마나과",
    country: "니카라과",
    timezone: "America/Managua",
    utcOffset: -6,
    timeStandard: "서머타임",
  },
  {
    id: "tegucigalpa",
    city: "테구시갈파",
    country: "온두라스",
    timezone: "America/Tegucigalpa",
    utcOffset: -6,
    timeStandard: "서머타임",
  },
  {
    id: "costa_rica",
    city: "산호세",
    country: "코스타리카",
    timezone: "America/Costa_Rica",
    utcOffset: -6,
    timeStandard: "서머타임",
  },

  // UTC-5
  {
    id: "new_york",
    city: "뉴욕",
    country: "미국",
    timezone: "America/New_York",
    utcOffset: -5,
    timeStandard: "서머타임",
    useDST: true,
  },
  {
    id: "toronto",
    city: "토론토",
    country: "캐나다",
    timezone: "America/Toronto",
    utcOffset: -5,
    timeStandard: "서머타임",
    useDST: true,
  },
  {
    id: "lima",
    city: "리마",
    country: "페루",
    timezone: "America/Lima",
    utcOffset: -5,
    timeStandard: "서머타임",
  },
  {
    id: "bogota",
    city: "보고타",
    country: "콜롬비아",
    timezone: "America/Bogota",
    utcOffset: -5,
    timeStandard: "서머타임",
  },
  {
    id: "kingston",
    city: "킹스턴",
    country: "자메이카",
    timezone: "America/Jamaica",
    utcOffset: -5,
    timeStandard: "서머타임",
  },
  {
    id: "panama",
    city: "파나마시티",
    country: "파나마",
    timezone: "America/Panama",
    utcOffset: -5,
    timeStandard: "서머타임",
  },
  {
    id: "havana",
    city: "하바나",
    country: "쿠바",
    timezone: "America/Havana",
    utcOffset: -5,
    timeStandard: "서머타임",
    useDST: true,
  },

  // UTC-4
  {
    id: "halifax",
    city: "핼리팩스",
    country: "캐나다",
    timezone: "America/Halifax",
    utcOffset: -4,
    timeStandard: "서머타임",
    useDST: true,
  },
  {
    id: "santiago",
    city: "산티아고",
    country: "칠레",
    timezone: "America/Santiago",
    utcOffset: -4,
    timeStandard: "서머타임",
    useDST: true,
  },
  {
    id: "caracas",
    city: "카라카스",
    country: "베네수엘라",
    timezone: "America/Caracas",
    utcOffset: -4,
    timeStandard: "서머타임",
  },
  {
    id: "la_paz",
    city: "라파스",
    country: "볼리비아",
    timezone: "America/La_Paz",
    utcOffset: -4,
    timeStandard: "서머타임",
  },
  {
    id: "santo_domingo",
    city: "산토도밍고",
    country: "도미니카 공화국",
    timezone: "America/Santo_Domingo",
    utcOffset: -4,
    timeStandard: "서머타임",
  },
  {
    id: "puerto_rico",
    city: "산후안",
    country: "푸에르토리코",
    timezone: "America/Puerto_Rico",
    utcOffset: -4,
    timeStandard: "서머타임",
  },

  // UTC-3
  {
    id: "sao_paulo",
    city: "상파울루",
    country: "브라질",
    timezone: "America/Sao_Paulo",
    utcOffset: -3,
    timeStandard: "서머타임",
    useDST: true,
  },
  {
    id: "buenos_aires",
    city: "부에노스아이레스",
    country: "아르헨티나",
    timezone: "America/Argentina/Buenos_Aires",
    utcOffset: -3,
    timeStandard: "서머타임",
  },
  {
    id: "montevideo",
    city: "몬테비데오",
    country: "우루과이",
    timezone: "America/Montevideo",
    utcOffset: -3,
    timeStandard: "서머타임",
    useDST: true,
  },
  {
    id: "asuncion",
    city: "아순시온",
    country: "파라과이",
    timezone: "America/Asuncion",
    utcOffset: -3,
    timeStandard: "서머타임",
    useDST: true,
  },

  // UTC-2
  {
    id: "fernando_de_noronha",
    city: "페르난두 지 노로냐",
    country: "브라질",
    timezone: "America/Noronha",
    utcOffset: -2,
    timeStandard: "서머타임",
  },
  {
    id: "south_georgia",
    city: "사우스조지아",
    country: "영국령",
    timezone: "Atlantic/South_Georgia",
    utcOffset: -2,
    timeStandard: "서머타임",
  },

  // UTC-1
  {
    id: "azores",
    city: "아조레스",
    country: "포르투갈",
    timezone: "Atlantic/Azores",
    utcOffset: -1,
    timeStandard: "서머타임",
    useDST: true,
  },
  {
    id: "cape_verde",
    city: "프라이아",
    country: "카보베르데",
    timezone: "Atlantic/Cape_Verde",
    utcOffset: -1,
    timeStandard: "서머타임",
  },

  // UTC+0
  {
    id: "london",
    city: "���던",
    country: "영국",
    timezone: "Europe/London",
    utcOffset: 0,
    timeStandard: "서머타임",
    useDST: true,
  },
  {
    id: "lisbon",
    city: "리스본",
    country: "포르투갈",
    timezone: "Europe/Lisbon",
    utcOffset: 0,
    timeStandard: "서머타임",
    useDST: true,
  },
  {
    id: "dublin",
    city: "더블린",
    country: "아일랜드",
    timezone: "Europe/Dublin",
    utcOffset: 0,
    timeStandard: "서머타임",
    useDST: true,
  },
  {
    id: "dakar",
    city: "다카르",
    country: "세네갈",
    timezone: "Africa/Dakar",
    utcOffset: 0,
    timeStandard: "서머타임",
  },
  {
    id: "accra",
    city: "아크라",
    country: "가나",
    timezone: "Africa/Accra",
    utcOffset: 0,
    timeStandard: "서머타임",
  },
  {
    id: "reykjavik",
    city: "레이캬비크",
    country: "아이슬란드",
    timezone: "Atlantic/Reykjavik",
    utcOffset: 0,
    timeStandard: "서머타임",
  },

  // UTC+1
  {
    id: "paris",
    city: "파리",
    country: "프랑스",
    timezone: "Europe/Paris",
    utcOffset: 1,
    timeStandard: "서머타임",
    useDST: true,
  },
  {
    id: "berlin",
    city: "베를린",
    country: "독일",
    timezone: "Europe/Berlin",
    utcOffset: 1,
    timeStandard: "서머타임",
    useDST: true,
  },
  {
    id: "rome",
    city: "로마",
    country: "이탈리아",
    timezone: "Europe/Rome",
    utcOffset: 1,
    timeStandard: "서머타임",
    useDST: true,
  },
  {
    id: "madrid",
    city: "마드리드",
    country: "스페인",
    timezone: "Europe/Madrid",
    utcOffset: 1,
    timeStandard: "서머타임",
    useDST: true,
  },
  {
    id: "amsterdam",
    city: "암스테르담",
    country: "네덜란드",
    timezone: "Europe/Amsterdam",
    utcOffset: 1,
    timeStandard: "서머타임",
    useDST: true,
  },
  {
    id: "brussels",
    city: "브뤼셀",
    country: "벨기에",
    timezone: "Europe/Brussels",
    utcOffset: 1,
    timeStandard: "서머타임",
    useDST: true,
  },
  {
    id: "vienna",
    city: "비엔나",
    country: "오스트리아",
    timezone: "Europe/Vienna",
    utcOffset: 1,
    timeStandard: "서머타임",
    useDST: true,
  },
  {
    id: "stockholm",
    city: "스톡홀름",
    country: "스웨덴",
    timezone: "Europe/Stockholm",
    utcOffset: 1,
    timeStandard: "서머타임",
    useDST: true,
  },
  {
    id: "oslo",
    city: "오슬로",
    country: "노르웨이",
    timezone: "Europe/Oslo",
    utcOffset: 1,
    timeStandard: "서머타임",
    useDST: true,
  },
  {
    id: "copenhagen",
    city: "코펜하겐",
    country: "덴마크",
    timezone: "Europe/Copenhagen",
    utcOffset: 1,
    timeStandard: "서머타임",
    useDST: true,
  },
  {
    id: "warsaw",
    city: "바르샤바",
    country: "폴란드",
    timezone: "Europe/Warsaw",
    utcOffset: 1,
    timeStandard: "서머타임",
    useDST: true,
  },
  {
    id: "budapest",
    city: "부다페스트",
    country: "헝가리",
    timezone: "Europe/Budapest",
    utcOffset: 1,
    timeStandard: "서머타임",
    useDST: true,
  },
  {
    id: "prague",
    city: "프라하",
    country: "체코",
    timezone: "Europe/Prague",
    utcOffset: 1,
    timeStandard: "서머타임",
    useDST: true,
  },
  {
    id: "lagos",
    city: "라고스",
    country: "나이지리아",
    timezone: "Africa/Lagos",
    utcOffset: 1,
    timeStandard: "서머타임",
  },
  {
    id: "tunis",
    city: "튀니스",
    country: "튀니지",
    timezone: "Africa/Tunis",
    utcOffset: 1,
    timeStandard: "서머타임",
    useDST: true,
  },
  {
    id: "algiers",
    city: "알제",
    country: "알제리",
    timezone: "Africa/Algiers",
    utcOffset: 1,
    timeStandard: "서머타임",
  },
  {
    id: "casablanca",
    city: "카사블랑카",
    country: "모로코",
    timezone: "Africa/Casablanca",
    utcOffset: 1,
    timeStandard: "서머타임",
    useDST: true,
  },

  // UTC+2
  {
    id: "athens",
    city: "아테네",
    country: "그리스",
    timezone: "Europe/Athens",
    utcOffset: 2,
    timeStandard: "서머타임",
    useDST: true,
  },
  {
    id: "istanbul",
    city: "이스탄불",
    country: "터키",
    timezone: "Europe/Istanbul",
    utcOffset: 2,
    timeStandard: "서머타임",
  },
  {
    id: "helsinki",
    city: "헬싱키",
    country: "핀란드",
    timezone: "Europe/Helsinki",
    utcOffset: 2,
    timeStandard: "서머타임",
    useDST: true,
  },
  {
    id: "bucharest",
    city: "부쿠레슈티",
    country: "루마니아",
    timezone: "Europe/Bucharest",
    utcOffset: 2,
    timeStandard: "서머타임",
    useDST: true,
  },
  {
    id: "sofia",
    city: "소피아",
    country: "불가리아",
    timezone: "Europe/Sofia",
    utcOffset: 2,
    timeStandard: "서머타임",
    useDST: true,
  },
  {
    id: "riga",
    city: "리가",
    country: "라트비아",
    timezone: "Europe/Riga",
    utcOffset: 2,
    timeStandard: "서머타임",
    useDST: true,
  },
  {
    id: "tallinn",
    city: "탈린",
    country: "에스토니아",
    timezone: "Europe/Tallinn",
    utcOffset: 2,
    timeStandard: "서머타임",
    useDST: true,
  },
  {
    id: "vilnius",
    city: "빌뉴스",
    country: "리투아니아",
    timezone: "Europe/Vilnius",
    utcOffset: 2,
    timeStandard: "서머타임",
    useDST: true,
  },
  {
    id: "cairo",
    city: "카이로",
    country: "이집트",
    timezone: "Africa/Cairo",
    utcOffset: 2,
    timeStandard: "서머타임",
  },
  {
    id: "johannesburg",
    city: "요하네스버그",
    country: "남아프리카공화국",
    timezone: "Africa/Johannesburg",
    utcOffset: 2,
    timeStandard: "서머타임",
  },
  {
    id: "khartoum",
    city: "하르툼",
    country: "수단",
    timezone: "Africa/Khartoum",
    utcOffset: 2,
    timeStandard: "서머타임",
  },

  // UTC+3
  {
    id: "moscow",
    city: "모스크바",
    country: "러시아",
    timezone: "Europe/Moscow",
    utcOffset: 3,
    timeStandard: "서머타임",
  },
  {
    id: "kiev",
    city: "키예프",
    country: "우크라이나",
    timezone: "Europe/Kiev",
    utcOffset: 3,
    timeStandard: "서머타임",
    useDST: true,
  },
  {
    id: "riyadh",
    city: "리야드",
    country: "사우디아라비아",
    timezone: "Asia/Riyadh",
    utcOffset: 3,
    timeStandard: "서머타임",
  },
  {
    id: "baghdad",
    city: "바그다드",
    country: "이라크",
    timezone: "Asia/Baghdad",
    utcOffset: 3,
    timeStandard: "서머타임",
  },
  {
    id: "doha",
    city: "도하",
    country: "카타르",
    timezone: "Asia/Qatar",
    utcOffset: 3,
    timeStandard: "서머타임",
  },
  {
    id: "kuwait",
    city: "쿠웨이트시티",
    country: "쿠웨이트",
    timezone: "Asia/Kuwait",
    utcOffset: 3,
    timeStandard: "서머타임",
  },
  {
    id: "nairobi",
    city: "나이로비",
    country: "케냐",
    timezone: "Africa/Nairobi",
    utcOffset: 3,
    timeStandard: "서머타임",
  },
  {
    id: "addis_ababa",
    city: "아디스아바바",
    country: "에티오피아",
    timezone: "Africa/Addis_Ababa",
    utcOffset: 3,
    timeStandard: "서머타임",
  },

  // UTC+3.5
  {
    id: "tehran",
    city: "테헤란",
    country: "이란",
    timezone: "Asia/Tehran",
    utcOffset: 3.5,
    timeStandard: "서머타임",
    useDST: true,
  },

  // UTC+4
  {
    id: "dubai",
    city: "두바이",
    country: "아랍에미리트",
    timezone: "Asia/Dubai",
    utcOffset: 4,
    timeStandard: "서머타임",
  },
  {
    id: "baku",
    city: "바쿠",
    country: "아제르바이잔",
    timezone: "Asia/Baku",
    utcOffset: 4,
    timeStandard: "서머타임",
  },
  {
    id: "yerevan",
    city: "예레반",
    country: "아르메니아",
    timezone: "Asia/Yerevan",
    utcOffset: 4,
    timeStandard: "서머타임",
  },
  {
    id: "tbilisi",
    city: "트빌리시",
    country: "조지아",
    timezone: "Asia/Tbilisi",
    utcOffset: 4,
    timeStandard: "서머타임",
  },
  {
    id: "muscat",
    city: "무스카트",
    country: "오만",
    timezone: "Asia/Muscat",
    utcOffset: 4,
    timeStandard: "서머타임",
  },

  // UTC+4.5
  {
    id: "kabul",
    city: "카불",
    country: "아프가니스��",
    timezone: "Asia/Kabul",
    utcOffset: 4.5,
    timeStandard: "서머타임",
  },

  // UTC+5
  {
    id: "karachi",
    city: "카라치",
    country: "파키스탄",
    timezone: "Asia/Karachi",
    utcOffset: 5,
    timeStandard: "서머타임",
  },
  {
    id: "tashkent",
    city: "타슈켄트",
    country: "우즈베키스탄",
    timezone: "Asia/Tashkent",
    utcOffset: 5,
    timeStandard: "서머타임",
  },
  {
    id: "ashgabat",
    city: "아슈하바트",
    country: "투르크메니스탄",
    timezone: "Asia/Ashgabat",
    utcOffset: 5,
    timeStandard: "서머타임",
  },
  {
    id: "dushanbe",
    city: "두샨베",
    country: "타지키스탄",
    timezone: "Asia/Dushanbe",
    utcOffset: 5,
    timeStandard: "서머타임",
  },
  {
    id: "ekaterinburg",
    city: "예카테린부르크",
    country: "러시아",
    timezone: "Asia/Yekaterinburg",
    utcOffset: 5,
    timeStandard: "서머타임",
  },
  {
    id: "maldives",
    city: "말레",
    country: "몰디브",
    timezone: "Indian/Maldives",
    utcOffset: 5,
    timeStandard: "서머타임",
  },

  // UTC+5.5
  {
    id: "new_delhi",
    city: "뉴델리",
    country: "인도",
    timezone: "Asia/Kolkata",
    utcOffset: 5.5,
    timeStandard: "서머타임",
  },
  {
    id: "mumbai",
    city: "뭄바이",
    country: "인도",
    timezone: "Asia/Kolkata",
    utcOffset: 5.5,
    timeStandard: "서머타임",
  },
  {
    id: "colombo",
    city: "콜롬보",
    country: "스리랑카",
    timezone: "Asia/Colombo",
    utcOffset: 5.5,
    timeStandard: "서머타임",
  },

  // UTC+5.75
  {
    id: "kathmandu",
    city: "카트만두",
    country: "네팔",
    timezone: "Asia/Kathmandu",
    utcOffset: 5.75,
    timeStandard: "서머타임",
  },

  // UTC+6
  {
    id: "dhaka",
    city: "다카",
    country: "방글라데시",
    timezone: "Asia/Dhaka",
    utcOffset: 6,
    timeStandard: "서머타임",
  },
  {
    id: "almaty",
    city: "알마티",
    country: "카자흐스탄",
    timezone: "Asia/Almaty",
    utcOffset: 6,
    timeStandard: "서머타임",
  },
  {
    id: "novosibirsk",
    city: "노보시비르스크",
    country: "러시아",
    timezone: "Asia/Novosibirsk",
    utcOffset: 6,
    timeStandard: "서머타임",
  },
  {
    id: "thimphu",
    city: "팀푸",
    country: "부탄",
    timezone: "Asia/Thimphu",
    utcOffset: 6,
    timeStandard: "서머타임",
  },

  // UTC+6.5
  {
    id: "yangon",
    city: "양곤",
    country: "미얀마",
    timezone: "Asia/Yangon",
    utcOffset: 6.5,
    timeStandard: "서머타임",
  },
  {
    id: "cocos",
    city: "코코스 제도",
    country: "호주령",
    timezone: "Indian/Cocos",
    utcOffset: 6.5,
    timeStandard: "서머타임",
  },

  // UTC+7
  {
    id: "bangkok",
    city: "방콕",
    country: "태국",
    timezone: "Asia/Bangkok",
    utcOffset: 7,
    timeStandard: "동경127.5도",
  },
  {
    id: "jakarta",
    city: "자카르타",
    country: "인도네시아",
    timezone: "Asia/Jakarta",
    utcOffset: 7,
    timeStandard: "동경127.5도",
  },
  {
    id: "hanoi",
    city: "하노이",
    country: "베트남",
    timezone: "Asia/Ho_Chi_Minh",
    utcOffset: 7,
    timeStandard: "동경127.5도",
  },
  {
    id: "phnom_penh",
    city: "프놈펜",
    country: "캄보디아",
    timezone: "Asia/Phnom_Penh",
    utcOffset: 7,
    timeStandard: "동경127.5도",
  },
  {
    id: "vientiane",
    city: "비엔티안",
    country: "라오스",
    timezone: "Asia/Vientiane",
    utcOffset: 7,
    timeStandard: "동경127.5도",
  },
  {
    id: "krasnoyarsk",
    city: "크라스노야르스크",
    country: "러시아",
    timezone: "Asia/Krasnoyarsk",
    utcOffset: 7,
    timeStandard: "동경127.5도",
  },

  // UTC+8
  {
    id: "beijing",
    city: "베이징",
    country: "중국",
    timezone: "Asia/Shanghai",
    utcOffset: 8,
    timeStandard: "동경127.5도",
  },
  {
    id: "shanghai",
    city: "상하이",
    country: "중국",
    timezone: "Asia/Shanghai",
    utcOffset: 8,
    timeStandard: "동경127.5도",
  },
  {
    id: "hong_kong",
    city: "홍콩",
    country: "중국",
    timezone: "Asia/Hong_Kong",
    utcOffset: 8,
    timeStandard: "동경127.5도",
  },
  {
    id: "taipei",
    city: "타이페이",
    country: "대만",
    timezone: "Asia/Taipei",
    utcOffset: 8,
    timeStandard: "동경127.5도",
  },
  {
    id: "singapore",
    city: "싱가포르",
    country: "싱가포르",
    timezone: "Asia/Singapore",
    utcOffset: 8,
    timeStandard: "동경127.5도",
  },
  {
    id: "kuala_lumpur",
    city: "쿠알라룸푸르",
    country: "말레이시아",
    timezone: "Asia/Kuala_Lumpur",
    utcOffset: 8,
    timeStandard: "동경127.5도",
  },
  {
    id: "manila",
    city: "마닐라",
    country: "필리핀",
    timezone: "Asia/Manila",
    utcOffset: 8,
    timeStandard: "동경127.5도",
  },
  {
    id: "perth",
    city: "퍼스",
    country: "호주",
    timezone: "Australia/Perth",
    utcOffset: 8,
    timeStandard: "동경127.5도",
  },
  {
    id: "makassar",
    city: "마카사르",
    country: "인도네시아",
    timezone: "Asia/Makassar",
    utcOffset: 8,
    timeStandard: "동경127.5도",
  },
  {
    id: "ulaanbaatar",
    city: "울란바토르",
    country: "몽골",
    timezone: "Asia/Ulaanbaatar",
    utcOffset: 8,
    timeStandard: "동경127.5도",
  },
  {
    id: "irkutsk",
    city: "이르쿠츠크",
    country: "러시아",
    timezone: "Asia/Irkutsk",
    utcOffset: 8,
    timeStandard: "동경127.5도",
  },

  // UTC+9
  {
    id: "seoul",
    city: "서울",
    country: "한국",
    timezone: "Asia/Seoul",
    utcOffset: 9,
    timeStandard: "동경135도",
  },
  {
    id: "busan",
    city: "부산",
    country: "한국",
    timezone: "Asia/Seoul",
    utcOffset: 9,
    timeStandard: "동경135도",
  },
  {
    id: "daegu",
    city: "대구",
    country: "한국",
    timezone: "Asia/Seoul",
    utcOffset: 9,
    timeStandard: "동경135도",
  },
  {
    id: "incheon",
    city: "인천",
    country: "한국",
    timezone: "Asia/Seoul",
    utcOffset: 9,
    timeStandard: "동경135도",
  },
  {
    id: "gwangju",
    city: "광주",
    country: "한국",
    timezone: "Asia/Seoul",
    utcOffset: 9,
    timeStandard: "동경135도",
  },
  {
    id: "daejeon",
    city: "대전",
    country: "한국",
    timezone: "Asia/Seoul",
    utcOffset: 9,
    timeStandard: "동경135도",
  },
  {
    id: "ulsan",
    city: "울산",
    country: "한국",
    timezone: "Asia/Seoul",
    utcOffset: 9,
    timeStandard: "동경135도",
  },
  {
    id: "jeju",
    city: "제주",
    country: "한국",
    timezone: "Asia/Seoul",
    utcOffset: 9,
    timeStandard: "동경135도",
  },
  {
    id: "tokyo",
    city: "도쿄",
    country: "일본",
    timezone: "Asia/Tokyo",
    utcOffset: 9,
    timeStandard: "동경135도",
  },
  {
    id: "osaka",
    city: "오사카",
    country: "일본",
    timezone: "Asia/Tokyo",
    utcOffset: 9,
    timeStandard: "동경135도",
  },
  {
    id: "sapporo",
    city: "삿포로",
    country: "일본",
    timezone: "Asia/Tokyo",
    utcOffset: 9,
    timeStandard: "동경135도",
  },
  {
    id: "kyoto",
    city: "교토",
    country: "일본",
    timezone: "Asia/Tokyo",
    utcOffset: 9,
    timeStandard: "동경135도",
  },
  {
    id: "fukuoka",
    city: "후쿠오카",
    country: "일본",
    timezone: "Asia/Tokyo",
    utcOffset: 9,
    timeStandard: "동경135도",
  },
  {
    id: "yakutsk",
    city: "야쿠츠크",
    country: "러시아",
    timezone: "Asia/Yakutsk",
    utcOffset: 9,
    timeStandard: "동경135도",
  },
  {
    id: "jayapura",
    city: "자야푸라",
    country: "인도네시아",
    timezone: "Asia/Jayapura",
    utcOffset: 9,
    timeStandard: "동경135도",
  },
  {
    id: "pyongyang",
    city: "평양",
    country: "북한",
    timezone: "Asia/Pyongyang",
    utcOffset: 9,
    timeStandard: "동경135도",
  },
  {
    id: "dili",
    city: "딜리",
    country: "동티모르",
    timezone: "Asia/Dili",
    utcOffset: 9,
    timeStandard: "동경135도",
  },

  // UTC+9.5
  {
    id: "adelaide",
    city: "애들레이드",
    country: "호주",
    timezone: "Australia/Adelaide",
    utcOffset: 9.5,
    timeStandard: "서머타임",
    useDST: true,
  },
  {
    id: "darwin",
    city: "다윈",
    country: "호주",
    timezone: "Australia/Darwin",
    utcOffset: 9.5,
    timeStandard: "서머타임",
  },

  // UTC+10
  {
    id: "sydney",
    city: "시드니",
    country: "호주",
    timezone: "Australia/Sydney",
    utcOffset: 10,
    timeStandard: "서머타임",
    useDST: true,
  },
  {
    id: "melbourne",
    city: "멜버른",
    country: "호주",
    timezone: "Australia/Melbourne",
    utcOffset: 10,
    timeStandard: "서머타임",
    useDST: true,
  },
  {
    id: "brisbane",
    city: "브리즈번",
    country: "호주",
    timezone: "Australia/Brisbane",
    utcOffset: 10,
    timeStandard: "서머타임",
  },
  {
    id: "hobart",
    city: "호바트",
    country: "호주",
    timezone: "Australia/Hobart",
    utcOffset: 10,
    timeStandard: "서머타임",
    useDST: true,
  },
  {
    id: "vladivostok",
    city: "블라디보스토크",
    country: "러시아",
    timezone: "Asia/Vladivostok",
    utcOffset: 10,
    timeStandard: "서머타임",
  },
  {
    id: "port_moresby",
    city: "포트모르즈비",
    country: "파푸아뉴기니",
    timezone: "Pacific/Port_Moresby",
    utcOffset: 10,
    timeStandard: "서머타임",
  },
  {
    id: "guam",
    city: "괌",
    country: "미국령",
    timezone: "Pacific/Guam",
    utcOffset: 10,
    timeStandard: "서머타임",
  },

  // UTC+11
  {
    id: "noumea",
    city: "누메아",
    country: "뉴칼레도니아",
    timezone: "Pacific/Noumea",
    utcOffset: 11,
    timeStandard: "서머타임",
  },
  {
    id: "magadan",
    city: "마가단",
    country: "러시아",
    timezone: "Asia/Magadan",
    utcOffset: 11,
    timeStandard: "서머타임",
  },
  {
    id: "solomon",
    city: "호니아라",
    country: "솔로몬 제도",
    timezone: "Pacific/Guadalcanal",
    utcOffset: 11,
    timeStandard: "서머타임",
  },

  // UTC+12
  {
    id: "auckland",
    city: "오클랜드",
    country: "뉴질랜드",
    timezone: "Pacific/Auckland",
    utcOffset: 12,
    timeStandard: "서머타임",
    useDST: true,
  },
  {
    id: "wellington",
    city: "웰링턴",
    country: "뉴질랜드",
    timezone: "Pacific/Auckland",
    utcOffset: 12,
    timeStandard: "서머타임",
    useDST: true,
  },
  {
    id: "fiji",
    city: "수바",
    country: "피지",
    timezone: "Pacific/Fiji",
    utcOffset: 12,
    timeStandard: "서머타임",
    useDST: true,
  },
  {
    id: "kamchatka",
    city: "페트로파블롭스크캄차츠키",
    country: "러시아",
    timezone: "Asia/Kamchatka",
    utcOffset: 12,
    timeStandard: "서머타임",
  },
  {
    id: "marshall_islands",
    city: "마주로",
    country: "마셜 제도",
    timezone: "Pacific/Majuro",
    utcOffset: 12,
    timeStandard: "서머타임",
  },

  // UTC+13
  {
    id: "samoa",
    city: "아피아",
    country: "사모아",
    timezone: "Pacific/Apia",
    utcOffset: 13,
    timeStandard: "서머타임",
    useDST: true,
  },
  {
    id: "tonga",
    city: "누쿠알로파",
    country: "통가",
    timezone: "Pacific/Tongatapu",
    utcOffset: 13,
    timeStandard: "서머타임",
  },

  // UTC+14
  {
    id: "kiribati",
    city: "크리스마스 섬",
    country: "키리바시",
    timezone: "Pacific/Kiritimati",
    utcOffset: 14,
    timeStandard: "서머타임",
  },
]

// 도시 ID로 도시 데이터 찾기
export function getCityById(cityId: string): CityTimezoneData | undefined {
  return CITY_TIMEZONE_DATA.find((city) => city.id === cityId)
}

// 도시 이름으로 도시 검색
export function searchCities(query: string): CityTimezoneData[] {
  if (!query || query.trim() === "") {
    return CITY_TIMEZONE_DATA
  }

  const normalizedQuery = query.toLowerCase().trim()

  return CITY_TIMEZONE_DATA.filter(
    (city) => city.city.toLowerCase().includes(normalizedQuery) || city.country.toLowerCase().includes(normalizedQuery),
  )
}

// 기본 도시 ID (서울)
export const DEFAULT_CITY_ID = "seoul"
